name: Get IP
on: [workflow_dispatch]
jobs:
  get_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get IP
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $\{{ secrets.VPS_HOST }}
          username: $\{{ secrets.VPS_USERNAME }}
          key: $\{{ secrets.SSH_PRIVATE_KEY }}
          script: |
            curl -s ipinfo.io/ip

